### PR TITLE
Add deepcopy support

### PR DESCRIPTION
**Pull request by rassouly**
This PR enables users to use `deepcopy` with structures containing `FlexPath`, `RobustPath`, `Polygon`, or `Label`.
Without this patch, I get error messages about objects that cannot be pickled (which makes sense for objects defined in a C library).
The `__deepcopy__` special method is poorly documented but I believe that the only argument shouldn't be used by the callee and should just be passed along as an argument to recursive calls to `deepcopy`.

### CODE REVIEW

**Review by heitzmann — CHANGES_REQUESTED** [review]
Sounds good, but I have a few comments:
- it seems we have to include ourselves in the memo dictionary before returning: `memo[id(self)] = self_copy`
- the methods should be flagged `METH_VARARGS | METH_KEYWORDS` to accept the memo argument as a keyword. We also need to do all the parsing and error-checking of the `args` and `kwds` arguments to make sure we are passed an object with the mapping interface.
- add tests

**Comment by rassouly** [comment]
As I said in my first message, I am almost certain that we should treat memo as a black box. This special function is never called directly by the user (even in a `__deepcopy__` function, instead they are supposed to use the `deepcopy()` function in the copy module. The docs (https://docs.python.org/3/library/copy.html) say to treat memo as an opaque object and memoization is actually done by `deepcopy()` itself (see https://github.com/python/cpython/blob/1bbf60dc311443dfc7cd3c587745db0768bfe5dc/Lib/copy.py#L128).

Thus I also don't believe we shouldn't any argument verification since the type of memo is not defined in the API (and since we don't have any children to call `deepcopy `on, we don't need that argument at all).

I'll add tests which we'll be mostly duplicates of the `copy()` test.

**Comment by heitzmann** [comment]
I see, okay, so forget all the argument parsing. The functions should still be flagged `METH_VARARGS | METH_KEYWORDS`, though, even if we ignore both arguments. Let's not constrain the function call method if we don't have to (and users can definitely call `__deepcopy__` if they want to for whatever reason).

**Comment by rassouly** [comment]
I have added some tests. Let me know if you think that it's enough. They all pass on my Windows computer.

**Review by heitzmann — APPROVED** [review]

**Pull request merged**
