### PR TITLE
Add typing stub

### PR DESCRIPTION
**Pull request by rassouly**
This patch adds a stub file to add type information to the users of the python API. This patch was tested on VSCode (Pylance type-checker).
To distribute this stub file, it was necessary to move the C extension to gdstk.gdstk but all the names are then imported into the gdstk top level module so the users should not experience any breakage. (According to PEP 561, a single file package cannot have a type stub).
The stub file was generated by mypy but all the type information was added bu hand so mistakes are possible.
The type system of python has limitations so it doesn't accept all valid programs. For example, all points are required to be tuples or complex even though 2-elements list also work. (This was done to statically hint that the points have 2 coordinates).
This patch is based on #183 but is completely independent. I can rebase it if you want to merge it first.

### CODE REVIEW

**Comment by rassouly** [comment]
Rebased on main for cleaner history.

**Comment by rassouly** [comment]
Any updates on this?

**Comment by heitzmann** [comment]
Hi @rassouly, this is a pretty large change. I want to go through it carefully, but I can only work on gdstk on my spare time, so it can be a little while before I get to it. If you're in a hurry, in the meantime, you can release the stubs as a [separate package](https://peps.python.org/pep-0561/#stub-only-packages), as you probably know.

**Comment by rassouly** [comment]
No problem! Thank you for taking the time to review my patches!

**Review by heitzmann — CHANGES_REQUESTED** [review]
I had some time to review the changes and it looks good to me.

There are a couple of imports that are not supported in all versions of python which we support (3.7+). Maybe there are more, but the ones I identified are:
- `Literal` (3.8+)
- `Self` (3.11+)
It's probably better to add `typing_extensions` as an optional dependency and use it as a fallback when importing those.

`Any` is imported and not used.

Please run the black format tool on gdstk.pyi.

**Comment by rassouly** [comment]
Hi,
Python 3.7 is officially EOL but I added `typing_extensions` as a fallback.

**Comment by heitzmann** [comment]
Thanks!

**Pull request merged**
